/**
 * Program / Degree Presets
 * Covers Indian higher education programs and degrees through configuration.
 * All presets are marked as APPROXIMATIONS with an editable disclaimer.
 */

import { DegreeType, EntryType, TermSystem } from '../types';
import { UGC_10_POINT_SCHEME, AICTE_10_POINT_SCHEME, PERCENTAGE_DIVISION_SCHEME } from './grading-schemes';

export interface ProgramPreset {
  id: string;
  name: string;
  degree_type: DegreeType;
  duration_years: number;
  entry_type: EntryType;
  starting_term_number: number; // 1 for regular, 3 for lateral entry
  total_terms: number;
  term_system: TermSystem;
  default_grading_scheme_id: string;
  default_attendance_threshold: number;
  description: string;
  approximation_notice: string;
}

export const PROGRAM_APPROXIMATION_NOTICE =
  "Preset approximation: University durations, starting semesters, and grading policies vary. Verify with your college handbook and edit as necessary.";

export const ALL_PROGRAM_PRESETS: ProgramPreset[] = [
  {
    id: 'prog-btech-regular',
    name: 'B.Tech / B.E. (Regular 4 Years)',
    degree_type: 'BTech',
    duration_years: 4,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 8,
    term_system: 'semester',
    default_grading_scheme_id: AICTE_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: 'Standard 4-year, 8-semester Bachelor of Technology or Engineering curriculum.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-btech-lateral',
    name: 'B.Tech / B.E. (Lateral Entry - Starts Semester 3)',
    degree_type: 'BTech',
    duration_years: 3,
    entry_type: 'lateral',
    starting_term_number: 3, // Lateral entry enters directly into 2nd year (Semester 3)
    total_terms: 6,
    term_system: 'semester',
    default_grading_scheme_id: AICTE_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '3-year, 6-semester engineering program for diploma holders entering in semester 3.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-mtech',
    name: 'M.Tech / M.E. (Postgraduate 2 Years)',
    degree_type: 'MTech',
    duration_years: 2,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 4,
    term_system: 'semester',
    default_grading_scheme_id: AICTE_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '2-year, 4-semester Master of Technology or Engineering with thesis/project components.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-bca',
    name: 'BCA (Bachelor of Computer Applications 3 Years)',
    degree_type: 'BCA',
    duration_years: 3,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 6,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '3-year, 6-semester undergraduate computer science & applications program.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-mca',
    name: 'MCA (Master of Computer Applications 2 Years)',
    degree_type: 'MCA',
    duration_years: 2,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 4,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '2-year, 4-semester post-graduate degree in computer applications.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-bsc',
    name: 'B.Sc. (3 Years / 4 Years FYUP)',
    degree_type: 'BSc',
    duration_years: 3,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 6,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '3-year, 6-semester Bachelor of Science degree following UGC CBCS guidelines.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-msc',
    name: 'M.Sc. (Master of Science 2 Years)',
    degree_type: 'MSc',
    duration_years: 2,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 4,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '2-year, 4-semester post-graduate science program.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-bcom',
    name: 'B.Com. (Bachelor of Commerce 3 Years)',
    degree_type: 'BCom',
    duration_years: 3,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 6,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '3-year commerce program with accounting, taxation, and business law.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-mcom',
    name: 'M.Com. (Master of Commerce 2 Years)',
    degree_type: 'MCom',
    duration_years: 2,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 4,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '2-year post-graduate commerce degree.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-bba',
    name: 'BBA (Bachelor of Business Administration 3 Years)',
    degree_type: 'BBA',
    duration_years: 3,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 6,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '3-year, 6-semester business management program.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-mba',
    name: 'MBA (Master of Business Administration 2 Years)',
    degree_type: 'MBA',
    duration_years: 2,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 4,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 80,
    description: '2-year management curriculum with specialization and summer internships.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-ba',
    name: 'B.A. (Bachelor of Arts 3 Years)',
    degree_type: 'BA',
    duration_years: 3,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 6,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '3-year undergraduate arts and humanities program.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-ma',
    name: 'M.A. (Master of Arts 2 Years)',
    degree_type: 'MA',
    duration_years: 2,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 4,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '2-year postgraduate arts and humanities curriculum.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-barch',
    name: 'B.Arch (Bachelor of Architecture 5 Years)',
    degree_type: 'BArch',
    duration_years: 5,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 10,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '5-year, 10-semester architecture curriculum with studios and practical training.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-bpharm',
    name: 'B.Pharm (Bachelor of Pharmacy 4 Years)',
    degree_type: 'BPharm',
    duration_years: 4,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 8,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 80,
    description: '4-year pharmacy degree regulated by the Pharmacy Council of India (PCI).',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-llb',
    name: 'LL.B. (3-Year Law Program)',
    degree_type: 'LLB',
    duration_years: 3,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 6,
    term_system: 'semester',
    default_grading_scheme_id: PERCENTAGE_DIVISION_SCHEME.id,
    default_attendance_threshold: 70, // Bar Council of India minimum is 70%
    description: '3-year, 6-semester law degree under Bar Council of India standards.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-mbbs',
    name: 'MBBS (Bachelor of Medicine & Surgery 5.5 Years)',
    degree_type: 'MBBS',
    duration_years: 5,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 9, // Pre-clinical, Para-clinical, Clinical phases + internship
    term_system: 'annual',
    default_grading_scheme_id: PERCENTAGE_DIVISION_SCHEME.id,
    default_attendance_threshold: 75, // NMC mandates 75% theory, 80% practical
    description: 'Medical degree under National Medical Commission (NMC). Requires 75% theory / 80% practical.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-diploma',
    name: 'Diploma / Polytechnic (3 Years)',
    degree_type: 'diploma',
    duration_years: 3,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 6,
    term_system: 'semester',
    default_grading_scheme_id: PERCENTAGE_DIVISION_SCHEME.id,
    default_attendance_threshold: 75,
    description: '3-year technical diploma program following State Board of Technical Education rules.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-integrated',
    name: 'Integrated Dual Degree (5 Years - e.g. B.Tech + M.Tech / B.A. LL.B)',
    degree_type: 'integrated',
    duration_years: 5,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 10,
    term_system: 'semester',
    default_grading_scheme_id: AICTE_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: '5-year, 10-semester integrated dual degree program.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
  {
    id: 'prog-custom',
    name: 'Other / Custom Program',
    degree_type: 'other_custom',
    duration_years: 4,
    entry_type: 'regular',
    starting_term_number: 1,
    total_terms: 8,
    term_system: 'semester',
    default_grading_scheme_id: UGC_10_POINT_SCHEME.id,
    default_attendance_threshold: 75,
    description: 'Custom configuration for any college, university, or external diploma system.',
    approximation_notice: PROGRAM_APPROXIMATION_NOTICE,
  },
];

